feat: 把 asp, agp 抄過來
https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/aws/aws.plugin.zsh
https://stackoverflow.com/questions/49716583/how-to-temporarily-switch-profiles-for-aws-cli

diff --git a/zshrc/zsh_post_setup b/zshrc/zsh_post_setup
--- a/zshrc/zsh_post_setup
+++ b/zshrc/zsh_post_setup
@@ -34,7 +34,7 @@ explain () {
 # Git
 function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
 
-# awless
+# AWS
 if [ $commands[awless] ]; then
   awless() {
     unfunction "$0"
@@ -42,6 +42,41 @@ if [ $commands[awless] ]; then
     $0 "$@"
   }
 fi
+
+function agp() {
+  echo $AWS_PROFILE
+}
+
+function asp() {
+  if [[ -z "$1" ]]; then
+    unset AWS_DEFAULT_PROFILE AWS_PROFILE AWS_EB_PROFILE
+    echo AWS profile cleared.
+    return
+  fi
+
+  local -a available_profiles
+  available_profiles=($(aws_profiles))
+  if [[ -z "${available_profiles[(r)$1]}" ]]; then
+    echo "${fg[red]}Profile '$1' not found in '${AWS_CONFIG_FILE:-$HOME/.aws/config}'" >&2
+    echo "Available profiles: ${(j:, :)available_profiles:-no profiles found}${reset_color}" >&2
+    return 1
+  fi
+
+  export AWS_DEFAULT_PROFILE=$1
+  export AWS_PROFILE=$1
+  export AWS_EB_PROFILE=$1
+}
+
+function aws_profiles() {
+  [[ -r "${AWS_CONFIG_FILE:-$HOME/.aws/config}" ]] || return 1
+  grep '\[profile' "${AWS_CONFIG_FILE:-$HOME/.aws/config}"|sed -e 's/.*profile \([a-zA-Z0-9_\.-]*\).*/\1/'
+}
+
+function _aws_profiles() {
+  reply=($(aws_profiles))
+}
+
+compctl -K _aws_profiles asp
 
 # fzf
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
